### ISSUE TITLE
support for a larger config subset that k0sctl has

### ISSUE THREAD

**Issue by kaplan-michael** [Mirantis/terraform-provider-k0sctl#7]
**Is your feature request related to a problem? Please describe.**
Do you intend to support other k0sctl fields like bastion when connecting, or private addresses of hosts, etc?

**Describe the solution you'd like**
I'd like to use more of the config fields available in k0sctl 

**Additional context**
I have the bastion bit somewhat working locally(and will probably do the other bits I need too) 
Do you accept PRs at this time?

**Comment by kaplan-michael** [comment]
opened the PR with the changes already and added private_address, hostname and no taint flag.

**Comment by james-nesbitt** [comment]
Hi @kaplan-michael , these should be easy to merge in, I will take a look.

**Comment by kaplan-michael** [comment]
@james-nesbitt yeah, I'm closing the issue here.
